"""原创精灵像素画(16x16 字符矩阵)。'.' 为透明,其余字母查下方调色板。"""

BALL_ROWS = [
    "..kkkk..",
    ".krrrrk.",
    "krrrrrrk",
    "krrrrrrk",
    "kkkkkkkk",
    "kwwkkwwk",
    ".kwwwwk.",
    "..kkkk..",
]
BALL_PAL = {"k": (40, 40, 46), "r": (214, 60, 55), "w": (250, 250, 250)}

MON_ART = {
    # ---------- 草系初始:芽叶兽 ----------
    "sprout": {
        "pal": {"k": (45, 85, 45), "G": (95, 175, 72), "g": (60, 115, 52), "b": (142, 205, 105),
                "l": (208, 234, 168), "w": (255, 255, 255), "e": (32, 34, 44)},
        "rows": [
            "................",
            "....kk...kk.....",
            "...kGGk.kGGk....",
            "...kGGk.kGGk....",
            "....kkkGkkk.....",
            "......kgk.......",
            ".....kkkkk......",
            "....kbbbbbk.....",
            "..kbbbbbbbbbbk..",
            "..kbbwebbewbbk..",
            "..kbbeebbeebbk..",
            "..kbbbbbbbbbbk..",
            "..kbllllllllbk..",
            "...kbllllllbk...",
            "....kbbbbbbk....",
            ".....kk..kk.....",
        ],
    },
    # ---------- 草系进化:藤蔓兽 ----------
    "vine": {
        "pal": {"k": (38, 78, 38), "G": (78, 148, 58), "g": (52, 100, 45), "b": (115, 182, 88),
                "l": (192, 226, 160), "w": (255, 255, 255), "e": (32, 34, 44)},
        "rows": [
            "....kk...kk.....",
            "...kGGk.kGGk....",
            "....kkkGkkk.....",
            "......kgk.......",
            ".....kkkkk......",
            "....kbbbbbk.....",
            "...kbbbbbbbk....",
            "...kbbwebbewbk..",
            "..kbbbbbbbbbbk..",
            "..kgggbbbbbggk..",
            "..kbllllllllbk..",
            "..kbllllllllbk..",
            "...kbllllllbk...",
            "...kbbbbbbbbk...",
            "....kbk..kbk....",
            ".....k....k.....",
        ],
    },
    # ---------- 火系初始:火苗狐 ----------
    "foxf": {
        "pal": {"k": (125, 62, 30), "b": (235, 140, 60), "l": (250, 225, 180),
                "r": (226, 70, 45), "y": (255, 222, 92), "w": (255, 255, 255), "e": (40, 30, 26)},
        "rows": [
            "................",
            "..kk......kk....",
            ".kbbk....kbbk...",
            ".kbbbkkkkbbbk...",
            ".kbbbbbbbbbbk...",
            ".kbwbebbbewbbk..",
            ".kbblllllbbbk...",
            "..kbbbleebbbk...",
            "...kbbbbbbk.kk..",
            "..kbbbbbbbk.krk.",
            "..kbbbbbbbk.kryk",
            "..kblllllbbk.krk",
            "..kblllllbbk.kk.",
            "...kblllbbk.....",
            "...kbbbbbbk.....",
            "....kk..kk......",
        ],
    },
    # ---------- 火系进化:烈焰狐 ----------
    "firef": {
        "pal": {"k": (135, 45, 30), "b": (226, 92, 55), "l": (250, 212, 160),
                "r": (250, 150, 60), "y": (255, 226, 110), "w": (255, 255, 255), "e": (42, 28, 24)},
        "rows": [
            "................",
            "...kk.....kk....",
            "..kbbk...kbbk...",
            "..kbbbkkkbbbk...",
            "..kbbbbbbbbbk...",
            "..kbwbebbbewbk..",
            "..kbblllllbbk...",
            ".krbbbleebbbbrk.",
            ".krbbbbbbbbrk.kk",
            ".krbbbbbbbbrk.kr",
            ".kbllllllbbk.kry",
            ".kbllllllbbk.krk",
            "..kbllllbbk..kk.",
            "..kbbbbbbbk.....",
            "...kbbbbbk......",
            "...kk..kk.......",
        ],
    },
    # ---------- 水系初始:水泡龟 ----------
    "turtle": {
        "pal": {"k": (42, 62, 95), "b": (100, 160, 230), "l": (192, 226, 250),
                "d": (122, 132, 86), "g": (162, 172, 106), "w": (255, 255, 255), "e": (30, 34, 44)},
        "rows": [
            "................",
            "....kkkkkkkk....",
            "...kddddddddk...",
            "..kdgdggdggdk...",
            "..kddddddddddk..",
            ".kddddddddddddk.",
            ".kggggggggggggk.",
            "..kbbbbbbbbbbk..",
            "..kbwkebbekwbk..",
            "..kbbeebbeebbk..",
            "..kbbbbbbbbbbk..",
            "...kbllllllbk...",
            "...kbllllllbk...",
            "....kbbbbbbk....",
            "....kbk..kbk....",
            ".....k....k.....",
        ],
    },
    # ---------- 水系进化:浪涛龟 ----------
    "wave": {
        "pal": {"k": (36, 56, 112), "b": (72, 122, 216), "l": (172, 206, 246),
                "d": (92, 106, 70), "g": (132, 146, 92), "w": (255, 255, 255), "e": (28, 32, 46)},
        "rows": [
            "......g..g......",
            "....kkkkkkkk....",
            "...kddddddddk...",
            "..kdgdggdggdk...",
            "..kddddddddddk..",
            ".kddgddggddgddk.",
            ".kggggggggggggk.",
            "..kbbbbbbbbbbk..",
            "..kbwkebbekwbk..",
            "..kbbeebbeebbk..",
            "..kbbbbbbbbbbk..",
            "...kbllllllbk...",
            "...kbllllllbk...",
            "....kbbbbbbk....",
            "....kbk..kbk....",
            ".....k....k.....",
        ],
    },
    # ---------- 一般/飞行:麻雀雏 ----------
    "bird": {
        "pal": {"k": (92, 62, 40), "b": (182, 142, 92), "d": (142, 106, 66),
                "y": (250, 202, 82), "w": (255, 255, 255), "e": (34, 30, 28)},
        "rows": [
            "................",
            "......kkk.......",
            ".....kbbk.......",
            "....kbbbbk......",
            "...kbbbbbbk.....",
            "..kbwebbewbk....",
            "..kbbbbbbbbk....",
            ".kbbbbyybbbbbk..",
            ".kddddddddddk...",
            ".kbbbbbbbbbbk...",
            ".kbbbbbbbbbbk...",
            "..kbbbbbbbbk....",
            "...kbbbbbbk.....",
            "....kbbbbk......",
            "....kyk.kyk.....",
            ".....k...k......",
        ],
    },
    # ---------- 一般:啮齿鼠 ----------
    "rat": {
        "pal": {"k": (72, 72, 82), "b": (156, 156, 166), "l": (216, 216, 222),
                "p": (236, 172, 182), "w": (255, 255, 255), "e": (34, 32, 40)},
        "rows": [
            "................",
            "..kk......kk....",
            ".kbbk....kbbk...",
            ".kbpbk..kbpbk...",
            ".kbpbk..kbpbk...",
            ".kbbkkkkkkbbk...",
            ".kbbbbbbbbbbk...",
            ".kbwbebbbewbbk..",
            ".kbbbbbbbbbbk...",
            "..kbbbeebbbk....",
            "..kbllllllbk....",
            "..kbllllllbk....",
            "...kbbbbbbk.....",
            "...kbbbbbbk.....",
            "..kbk....kbk....",
            "..k........k....",
        ],
    },
    # ---------- 电:电鼠 ----------
    "pika": {
        "pal": {"k": (112, 86, 40), "b": (250, 220, 82), "d": (82, 62, 36),
                "r": (236, 96, 76), "w": (255, 255, 255), "e": (36, 30, 26)},
        "rows": [
            "................",
            "...kk......kk...",
            "..kddk....kddk..",
            "..kbbk....kbbk..",
            "..kbbk....kbbk..",
            "...kbbkkkkbbk...",
            "...kbbbbbbbbk...",
            "...kbrbbbbrbk...",
            "...kbewbbwebk...",
            "...kbbbbbbbbk.k.",
            "....kbbbbbbk.kk.",
            "...kbbbbbbbbkdk.",
            "...kbbbbbbbbk.k.",
            "....kbbbbbbk.dd.",
            "....kbk..kbk....",
            ".....k....k.....",
        ],
    },
    # ---------- 岩石/地面:小岩蛇 ----------
    "rock": {
        "pal": {"k": (62, 62, 72), "b": (142, 142, 152), "d": (102, 102, 114),
                "l": (182, 182, 192), "w": (255, 255, 255), "e": (30, 30, 38)},
        "rows": [
            "................",
            ".....kkkkkk.....",
            "....kbbbbbbk....",
            "...kbbdbbdbbk...",
            "..kbbbbbbbbbbk..",
            "..kbbwebbewbbk..",
            "..kbbbbbbbbbbk..",
            ".kbbbddbbddbbbk.",
            ".kbdbbbbbbbdbk..",
            ".kbbbbdbbbbbbbk.",
            ".kbbbbbbbbbbbbk.",
            "..kbddbbbbddbk..",
            "..kbbbbbbbbbbk..",
            "...kkbbbbbbkk...",
            ".....kkkkkk.....",
            "................",
        ],
    },
    # ---------- 岩石/地面进化:岩铠兽 ----------
    "boulder": {
        "pal": {"k": (56, 56, 66), "b": (152, 152, 162), "d": (106, 106, 120),
                "l": (192, 192, 202), "w": (255, 255, 255), "e": (28, 28, 36)},
        "rows": [
            "................",
            "....kkkkkkkk....",
            "...kbblbblbbk...",
            "..kbbbbbbbbbbk..",
            "..kblbbdbblbbk..",
            ".kbbwkebbekwbbk.",
            ".kbbbbbbbbbbbbk.",
            "kbbbbddbbddbbbbk",
            "kbbbbbbbbbbbbbbk",
            ".kbbbdddbbdddbk.",
            ".kbbbbbbbbbbbbk.",
            "..kbbdbbbbbdbk..",
            "..kbbbbbbbbbbk..",
            "...kkbbbbbbkk...",
            ".....kkkkkk.....",
            "................",
        ],
    },
}
